version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "9003:9003" 
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_DATABASE: expenses
      MYSQL_ROOT_PASSWORD: expenses2024
      MYSQL_USER: expenses
      MYSQL_PASSWORD: password
      QUEUE_CONNECTION: redis 
      MAIL_HOST: mailcatcher 
      MAIL_PORT: 1025 

    depends_on:
      - db
      - redis 
      - mailcatcher 

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: expenses
      MYSQL_ROOT_PASSWORD: expenses2024
      MYSQL_USER: expenses
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine 

  mailcatcher:
    image: schickling/mailcatcher 
    ports:
      - "1080:1080" 
      - "1025:1025"

volumes:
  db_data: